### PR TITLE
Add release notes for 4.5.7.

### PR DESCRIPTION
**Pull request by nojaf**

### CODE REVIEW

**Comment by cgravill** [comment]
This release is dedicated both F# Colins ;-)

**Comment by nojaf** [comment]
Oh boy, sorry about that 😅.
I linked the wrong Colin in my release notes 🙃

**Comment by nojaf** [comment]
Corrected https://github.com/fsprojects/fantomas/releases/tag/v4.5.7 🙈

**Comment by cgravill** [comment]
Ha no problem. The other Colin is excellent too!

**Pull request merged**
