### PR TITLE
Document the behaviour of Rider regarding default settings

### PR DESCRIPTION
**Pull request by dawedawe**
I think this is currently affecting quite some users (@edgarfgp, @aklefdal, ...) , so let's document it.

### CODE REVIEW

**Comment by aklefdal** [comment]
Thank you, @dawedawe, I was about to propose the same change myself 😊

**Review by nojaf — CHANGES_REQUESTED** [review]
Hello, I'm on board with this documented but not without a link to a YouTrack issue where this is officially reported to the Rider team.

Us having documentation is just dancing around the original problem.

**Comment by dawedawe** [comment]
> Hello, I'm on board with this documented but not without a link to a YouTrack issue where this is officially reported to the Rider team.
> 
> Us having documentation is just dancing around the original problem.

Here we go:
https://youtrack.jetbrains.com/issue/RIDER-83997/Rider-doesnt-respect-Fantomas-default-settings-not-explicitly-set-in-editorconfig

**Review by nojaf — APPROVED** [review]
Looks good!

**Comment by auduchinok** [comment]
Rider defaults were copied from Fantomas some time ago, way before Fantomas started using editor config files. The defaults have changed in Fantomas since then, and this was the reason Rider defaults started to differ.

@DedSec256 has just updated our defaults to match the current Fantomas ones in upcoming Rider 2022.3. It's not good in the long term, as Fantomas defaults may change again, rendering our defaults obsolete, so we're going to find a way to not hardcode these defaults in a later release (which is not that easy, because we need at least some defaults in R# settings, as they are used by refactorings, quick fixes, and other features).

**Pull request merged**
