### PR TITLE
Delete spaces for named arguments

### LINKED ISSUE #1877: Named argument should not have a space
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKAbRAXMBbAhgNaIDKWATovrgEpVLlgAeYAvGAHaIDuYJAngGcsiXADoAkgHkxZStTr4GACgAO%2BLAAtWTAJQAdcvo6QANOCiDsWAJYcA5oNRgA2hYigIXqABIs-VWQ0SDssM3cvSB8AN3x0AFcg1wjvAAZzb29ICQ4kDiwSGwAvZAzMiAAWFLAAXQiAXzKPaqj-QOcQ-PDyqNiEpLdyiABGJszIAFl8JgAZO0QZxActbqHhgCZU6rrvRojPcb8ApMgAI1hYdFWsmLjE50Gh9bGsklEbOHRYDgBBLABRXJSABmcy410ywLiVm2DTGBxubRO50uEIgvTuA2qEAAzC9IiR1NBEAAhRDA2CUAAK%2BHI1GwiHIaK8FESsN28JaR3awRRV3xGP6D2xYAq%2BPRhPwxLJFMoM1g3EZ0HwVhy0Vgyts32ZEFZiHZXj23gRkW5yIu-K5fXuaEe5QArOKoJLpeTKYgAKqqQLkZWqjjqzU2bVOqHoGHlHaGzk9M0dPnMwU25JDMAANidkBdpLdlAAwugVYI899hOR4tAsJSdWAwxHMlGIEavCb0XHeRbE7chbaRQB2TPZmXuiaiU6Mmt1-WRuH7LlI%2BOdgXd5N2zIADkHRJzssQJa%2BJlD0OnDdnxvnx0XqOX1qxqYAnFupYgfsCROQS7gCDW9QamzHDgXDtrytTFhVTYZ0hFLNt2HSg3lwD5LhDEUpz-MBm2aWMgKgBMbzA3sINGaDs1fd8EKQg8f3LE9vEbDCAMRS9gMtWNb3AtZnmgnI8iwKQOAAFXIfgAHUbBWI9w1orx6MwsBW18HCziXUCexTNY8RI7cfnIWB4lyAARRB0BsRD32otkZw5OdsOYqBQi7djCLWMVoKmJgJGBATNCWf4pJITRKSwMT4AkkUKi2KzoxswC7M6MJ8LUtdvGGR03OmHJgRsJgpB9DRKX%2BJhVEoQRBGDQ8RXtSLT2s89bJ5eyukS1cRWGDN0qYOg4HIeAQrC1MIvQuSFNaOKHOau81gHDquspeAADl4lwcdyBBCQRFwJwnWGIbGNNJTcHidBbBMrgADFKQILB3wEy8Jo48phk3aDZp6iYjpO%2BYLvIK7zMzaBNFpKV3wAfW4GxQs0SBdpipiGvixyCPUx7Hw6nS6X4KRyDmYQ%2Bqhp1Bqi-9Yf2samtUlrU02TN3PR-BMexmxhEW5bGTWjattamG6ti%2BHDuOmxTsQb7fsZW72nu5zynWYjU0gOmGZxrB3oFoWRY0P7oIBoHK0ZMGIZWbmWwveHxopybpa4uX3IANUxEk7HgOx7DxmtCZq6Kebhk4zbYpHkq8dZNOt6Yzv0ytyod3Jnddgnqros9jfqn3yb9pKRXWVyQ6YAzYCwABxbBCuKxBSvK2PKvjmTE6w3nzRAtPKaeNLrY%2BwX5hJL5oEIEk6W77BBH4kh6X3JaKtTNCiYYkm2yUvDzYezJ1nauX5p4IWySwRUlnFxAjKyjhxPKn5clHVnyE5ifjyN2vvavVjDic5Gl%2BmuWAGlEEQVRPO8pYcmH3ACx5iTmvlPYaJsU4JQXlLJez1s5%2BUQoITQFcBpVwgLJPas84rz0bhbJeqM5aFAcJgHS9glpLGCogU4EwEClFQqAj2xMvak3hjgx%2B-sRQ4ignLH4Jl7AcDDhwCO3xCj8I0PESgAlYA8QoRocqICpI33khA%2B%2BiN06phxLLIY8tjqMg4HI6ICxvj2DPitfedgj6lgUfWBOtUk511UZLZ%2B3gcRW20SrWwYIFjUFOPAfABZYBlQcGvbgQtrHSXQTXZRydHHQOcV4HEwdtEGSZvgU4mAEFM00AIfI0xwlKJGu2KASx4Agi8WQfgmA1FN3KDiLO2jASlNBMA-65B0DAmhmAzBilsEqVwYvFxLdtEfy-jI-IORe74CEfjehiiukzx6awvp7D1FDBxCvbRncpmEC8YIHSelchr2EIgeAHj25cGLiVMqVinS-nmcwrBSyG4rJqZkHEr9Nm0jgnvJm0ByCmTsBoE5HpD7fCMtAQsdItTjyGJPRh08HmLPrg-G4T8A64jgdouQHxla0PyWAiwNQyghEEGdMqzg0L1CAA)

#### Code

```fsharp
let makeStreamReader x = new System.IO.StreamReader(path=x)

```
            

#### Result

```fsharp
let makeStreamReader x = new System.IO.StreamReader(path = x)

```
            
#### Problem description

The style guide advises to not have spaces here.
> Named arguments should also not have space surrounding the =:

#### Extra information

- [ ] The formatted result breaks by code.
- [ ] The formatted result gives compiler warnings.
- [ ] I or my company would be willing to help fix this.

#### Options

Fantomas Master at 08/19/2021 16:27:53 - a80f888cbb71e8d0bd65d05c6ceccf9502d30f69

Default Fantomas configuration

<sub>Did you know that you can ignore files when formatting from fantomas-tool or the FAKE targets by using a [.fantomasignore file](https://github.com/fsprojects/fantomas/blob/master/docs/Documentation.md#ignore-files-fantomasignore)?</sub>

### PR DESCRIPTION
**Pull request by Viridovics**
Fixes #1877

### CODE REVIEW

**Comment by nojaf** [comment]
Hello @Viridovics, thank you for this first contribution to Fantomas.

There are a few things though, which you could not have known:
- As you are changing the style, this PR should be targeting the [4.7 branch](https://github.com/fsprojects/fantomas/tree/4.7).
The reasoning behind this is that we can bugfix the 4.6 release on the master branch and process every new feature or stylistic change on the next minor. I really should document this, apologies.
- @dsyme and I spoke at a conference in Oslo, and there I vaguely remember some doubts about this part of the style guide. Although it is published, it was still a bit of a pending topic whether it should have been.
- Looking at the multiline example, it feels very weird to me to still keep the equals after the name
```fsharp
SomeFunction(
    name=
        SearchForName(
            "foooooooooooooooooooooooooooooooooooooooooooooooooo",
            "baaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaar"
        )
)
```
It just looks like `name=` in total is the identifier. Also, this multiline example isn't particularly mentioned in the [style guide](https://docs.microsoft.com/en-us/dotnet/fsharp/style-guide/formatting#formatting-named-arguments). It really should be in there as the next person is going to open an issue that Fantomas is doing something not specified by the guide.
- Taking a step back, in defence of keeping the space, we do put a space for record fields. Would it not make more sense to align these? Just a thought.
```fsharp
{ name =
    SearchForName(
        "foooooooooooooooooooooooooooooooooooooooooooooooooo",
        "baaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaar"
    ) }
```
- I would also like to hear the opinion of the G-Research style guide on this. Perhaps we would need a setting to control this.
@Smaug123 and @kojo12228 would you mind bringing this up in the team?
- The current PR doesn't take patterns into account, if we are to have this, we should also include support for this:
```fsharp
let examineData x =
    match data with
    | OnePartData(part1=p1) -> p1
    | TwoPartData(part1=p1; part2=p2) -> p1 + p2
```

Excuses for all these open questions, I wholeheartedly understand this is might not feel like a welcoming experience for your first PR. Changing the style is just a very delicate course of action in Fantomas. Once this is merged, in my experience someone will challenge this greatly and be annoyed that *the style changed again*.

@dsyme, @Smaug123 and @kojo12228 could you respond to my questions above? Many thanks!

PS: @dsyme, out of interest, would there be any room to have a special named argument expression node in the AST?
The infix application with the equals sign feels more like a hack than an actual representation. Would this be ok to have? Would simplify Fantomas a bit.

**Comment by Smaug123** [comment]
The GR style guide says "Named arguments should also not have space surrounding the `=`", but this situation essentially never arises internally and I don't think we have a strong opinion. We'll ask the team, though.

**Comment by Smaug123** [comment]
Yeah, we don't have a strong opinion and will align with Microsoft, whatever you decide.

**Comment by nojaf** [comment]
Alright, thanks for confirming.

**Comment by Viridovics** [comment]
Hello @nojaf !

Thank you for detailed review!

Created list needed fixes:
- [ ] change destination branch to 4.7
- [ ] restore space for multiline function argument
- [ ] delete spaces for single line pair of `NamePatPairs`

**Comment by nojaf** [comment]
Hi @Viridovics, thanks for the additional changes for SynPat.

> restore space for multiline function argument

We don't really have a consensus on this yet. I mentioned that I found the absence of a space weird in the multiline assignment but that doesn't mean we need to go with it. I would really like to hear @dsyme his thoughts on this.

In a perfect world, all of the stylistic debate would already have been done at [fsharp/fslang-design](https://github.com/fsharp/fslang-design#style-guide). But as I mentioned, I recall some doubt on the topic.
So, we need to verify this first before we ship a change in Fantomas.
The ripple effect is quite huge when people would update to 4.7, every codebase using Fantomas would be affected.
Thanks for understanding.

**Comment by dsyme** [comment]
The current style guide says "no spaces", and all the code I personally write by hand has "no spaces" and so the current style guide reflects the visual expectations the language was originally designed for.

However when I started using Fantomas more I found myself thinking this may have been a relic of an overly cramped, compact coding style.  Looking at the samples in the tests I still find myself thinking this.

@Smaug123 Do you really not have a strong preference?

**Comment by Smaug123** [comment]
@dsyme Maybe a very mild personal preference for having more spaces, but it really doesn't arise much on the code I'm used to (which strongly prefers a single record containing config, rather than named arguments).

**Comment by auduchinok** [comment]
@dsyme I find the no-space style too cramped and quite different from other similar places in the language where we do have spaces: we either have spaces on the both sides (binary operator expressions, tuple types, bindings, etc), or a space after the separator (tuple expressions and patterns, parameters, typed expressions), so I always put spaces for named arguments and patterns, and it looks kind of more inline with the rest of the language to me (but maybe it requires some getting used to).

Maybe we could have a setting here? At least, if we don't change the default to have spaces 😅

**Comment by nojaf** [comment]
I honestly think we should keep the space as it will be more consistent with the rest of the language.
Just this morning I wrote:
```fsharp
match x with
| SynExpr.TryFinally (trivia={ TryKeyword = mTry })  -> mTry
```

It is weird to explain to a newcomer, that there should be no space for `trivia`, but one inside the record.

**Comment by knocte** [comment]
>I honestly think we should keep the space
> It is weird to explain to a newcomer, that there should be no space for trivia, but one inside the record.

Completely agree with this.

**Comment by dsyme** [comment]
> I honestly think we should keep the space

OK, given the collected feedback we will keep the spaces.  Can someone submit a PR to change the style please?

Thanks
Don

**Comment by nojaf** [comment]
> Can someone submit a PR to change the style guide please?

Yes, I can pick this up later this week.

@Viridovics I'm sorry this might have been an anticlimatic outcome for you. If you were rooting to remove the space in Fantomas, I understand this can be very frustrating.

I still think your changes are an improvement in `CodePrinter.fs`, we could keep those.
Since the style no longer changes, you can target the master branch again.

Thank you for understanding and thank you for your patience

**Comment by Viridovics** [comment]
Hello @nojaf !

I've changed destination branch to master. Should I change anything else in this PR?

**Comment by nojaf** [comment]
Hi @Viridovics! Well, given the outcome of this discussion, the space should be present again.
So, this impacts any new tests you have written and you need to revert the existing tests.

**Comment by nojaf** [comment]
Oh, and you might want to rebase again the latest master.

**Comment by nojaf** [comment]
Hi @Viridovics, I'm sorry for this next request but as the style guide was updated, the normal flow of Fantomas will actually already lead to the desired outcome.
I tested this locally and reverting all changes to CodePrinter will lead to all tests passing (including the new ones).
So, in that case, I'm in favour of less is more. Could you revert the changes to CodePrinter, please?
Sorry, for all the hassle.

**Comment by Viridovics** [comment]
Hi @nojaf, no problem. I've reverted CodePrinter.fs. Keeped only new unit tests.

**Review by nojaf — APPROVED** [review]

**Pull request merged**
