### PR TITLE
add space around binary operators in units of measure

### PR DESCRIPTION
**Pull request by dawedawe**
Fixes still open part of #2207

As Don has already [agreed](https://github.com/fsharp/fslang-design/issues/660#issuecomment-1138847319) to do it like this and there is a [PR](https://github.com/dotnet/docs/pull/29657) pending for the style guide clarification, I think we can move on with this.

I changed the test to use `*` instead of `/` because we have another test which already covers SynMeasure.Divide.

### CODE REVIEW

**Comment by nojaf** [comment]
Hey David, amazing that you are seeing this through.
Each individual piece of the process for a style change doesn't take that much.
But putting them together always seems a hurdle for most people, thanks for going the extra mile here.

In the spirit of leading by example, I'd like to merge this PR after the style guide gets published.
There have been some situations in the past where a link of a comment on a thread about the style guide was deemed significant to move on here on Fantomas' side.
However, I'm not a fan of this at all. It's in the guide or it isn't, how it got there is of no significance to Fantomas.

**Review by nojaf — APPROVED** [review]

**Comment by dawedawe** [comment]
> In the spirit of leading by example, I'd like to merge this PR after the style guide gets published. There have been some situations in the past where a link of a comment on a thread about the style guide was deemed significant to move on here on Fantomas' side. However, I'm not a fan of this at all. It's in the guide or it isn't, how it got there is of no significance to Fantomas.

Sure, I'm totally okay with waiting. I was just a bit eager with this, as I'm going on vacation and I'll be without a good coding setup for quite a while.

**Comment by nojaf** [comment]
Great, thanks for understanding. I'll take care of this as soon as the guide is published.

**Comment by nojaf** [comment]
I just learned about the [style-guide-decided](https://github.com/fsharp/fslang-design/issues/660#issuecomment-1138847319), which is good enough for me.

**Pull request merged**
