### PR TITLE
Add Spectr.Console

### PR DESCRIPTION
**Pull request by nojaf**
Adding Spectr to the project, I think this would be relevant later for https://github.com/fsprojects/fantomas/issues/2751.

image

### CODE REVIEW

**Comment by dawedawe** [comment]
Mmh, GitHub Actions seems to have some problem with the color coding:
`3852mFormatted0m  0  Ignored  0  38512mUnchanged0m  0  3859mErrored0m  0`

Besides from that, the PR looks good to me.

But I wonder if it's a good idea to have another output technique besides Serilog?
It does feel somewhat strange to me but I also can't think of a scenario in which it might cause some real issues 🤷‍♂️

**Comment by nojaf** [comment]
> But I wonder if it's a good idea to have another output technique besides Serilog?

We (ab)use Serilog right now predominantly for the difference in log levels.
It would be straightforward to get rid of that and log everything using Spectr.Console.

**Comment by dawedawe** [comment]
Ok, makes sense.
I'll approve as soon as we find the right steps to dance with the tests in github actions...

**Comment by nojaf** [comment]
I'm also having some second thoughts about what we should show when you target a single file.
See this with only 1 file is kinda overkill:

**Review by dawedawe — APPROVED** [review]

**Pull request merged**
