### PR TITLE
Fix for FCS API changes

### PR DESCRIPTION
**Pull request by auduchinok**
Once a new FCS package version is released this PR will fix the broken API usages.

### CODE REVIEW

**Comment by nojaf** [comment]
Thanks @auduchinok! Less changes than I expected.
Any idea how many tests are broken by the new FCS?

//cc: @baronfel

**Comment by auduchinok** [comment]
All is green for me locally.

**Comment by nojaf** [comment]
Oh that is great to hear, I was expecting some things to break due to the range fixes.
Main area of concern was the assignment of trivia to nodes.

**Comment by baronfel** [comment]
That's a bit concerning to me, because I have a new FCS locally and have been working on this same PR, and I have over 100 broken tests. These changes were just the tip of the iceberg for me.

**Comment by auduchinok** [comment]
Hm, I checked it on our FCS build and it _could_ have some difference, though, I wouldn't expect it. Let's look at it when FCS is released then.

**Pull request merged**
