### PR TITLE
Create MAINTAINERS.md

### PR DESCRIPTION
**Pull request by demarillacizere**
The list of maintainers have been provided by G-Research OSS.

### CODE REVIEW

**Comment by dawedawe** [comment]
Hey @demarillacizere,
thanks for this PR.
I'd like to wait till Florian is back from his vacation before merging this. The reason is, I can't judge his opinion on such a file for this project.

**Comment by demarillacizere** [comment]
> Hey @demarillacizere, thanks for this PR. I'd like to wait till Florian is back from his vacation before merging this. The reason is, I can't judge his opinion on such a file for this project.

No problem, Thanks!

**Comment by nojaf** [comment]
Hi @demarillacizere, Thanks for this first PR!
I think this is fine to have.
Would you mind adding:
- @dawedawe 
- @josh-degraw 

to the file as well?
I'm quite sure both are okay with this.

**Comment by demarillacizere** [comment]
> Hi @demarillacizere, Thanks for this first PR! I think this is fine to have. Would you mind adding:
> 
> * @dawedawe
> * @josh-degraw
> 
> to the file as well? I'm quite sure both are okay with this.

Sure, I've updated the file.

**Review by nojaf — APPROVED** [review]
Thanks @demarillacizere!

**Pull request merged**
