### PR TITLE
Use Ionide.Analyzers

### PR DESCRIPTION
**Pull request by nojaf**
Trying out https://github.com/ionide/ionide-analyzers

### CODE REVIEW

**Comment by nojaf** [comment]
@dawedawe any thoughts why we are not seeing these warnings?

**Comment by dawedawe** [comment]
> @dawedawe any thoughts why we are not seeing these warnings?

They are at least here:
https://github.com/fsprojects/fantomas/security/code-scanning?query=pr%3A2978+tool%3AIonide.Analyzers.Cli+is%3Aopen

To me, it seems a bit like the visual behaviour of GitHub is not really deterministic regarding these things.
Maybe the GitHub bot creates comments only for the first PR that adds the code scanning feature 🤷

**Comment by nojaf** [comment]
I admit defeat when it comes to `AnalyzeFSharpProjectUsingFscArgs`, I'll explain in more detail in the SDK repository.

Besides that, this is ready for review.

**Review by dawedawe — APPROVED** [review]
Turns out, analyzers can really improve a codebase :)

**Pull request merged**
