### PR TITLE
Bump FCS to 28.0.0 and use net461

### PR DESCRIPTION
**Pull request by nosami**

### CODE REVIEW

**Comment by nojaf** [comment]
Hi @nosami, Travis is failing due to a network problem when downloading packages inside a container.
Could you add `--network=host` after both `run` command in [.travis.yml](https://github.com/fsprojects/fantomas/blob/master/.travis.yml#L15)? That could resolve the issue.

**Comment by nosami** [comment]
Ok. Done! No idea if that is right. Will soon see :)

**Comment by nojaf** [comment]
Hi @nosami, thanks your change is exactly what it should be.
However, I just received word from Travis that the workaround shouldn't be needed anymore:
image
Could you revert the last change please? Sorry this is such a hassle.

**Comment by nosami** [comment]
No problem! Let's see if this works.

**Comment by nojaf** [comment]
Thanks, if you need it you can find the latest version on [MyGet](https://www.myget.org/gallery/fantomas) for now. It might take some time until the next official version is released.

**Comment by nojaf** [comment]
@nosami could you try https://www.myget.org/gallery/fantomas?

**Comment by nojaf** [comment]
@nosami could you try https://www.myget.org/gallery/fantomas please?

**Comment by nosami** [comment]
@nojaf Perfect, thanks!

**Pull request merged**
