### PR TITLE
Fix for preserve EOL feature

### PR DESCRIPTION
**Pull request by s-trooper**
the code formatted with ```preserveEOL``` feature will be broken and cannot compile, that PR should fix related issues.

P.S: PR #271  have to be accepted before, because a part of changes is based upon.

### CODE REVIEW

**Comment by nojaf** [comment]
@s-trooper  AppVeyor is working again, could you add an additional commit to trigger it?

**Comment by nojaf** [comment]
Hey @s-trooper, could you resolve the conflict? And I'm guessing this needs a bit of rework since we are not going with `let mutable CompilationDefines: string list = []` in #271

**Comment by s-trooper** [comment]
Hi @nojaf, i've looked and updated this RP. The `CompilationDefines` rework has not effected this PR features.

**Comment by nojaf** [comment]
Thanks @s-trooper

**Pull request merged**
