### PR TITLE
Bump SDK to 8.0.300

### PR DESCRIPTION
**Pull request by nojaf**

### CODE REVIEW

**Comment by Numpsy** [comment]
Are the ```Failed to inline the value 'getLambdaBodyExpr' marked 'inline'``` warnings in the build a result of https://github.com/dotnet/fsharp/issues/17161 or something else?

**Comment by nojaf** [comment]
No clue, feel free to investigate.

**Comment by baronfel** [comment]
It's a bug in the 300 release for F# - wait for this month's patch release and then go right to that one, by setting it as the min bar in your global.json.

**Comment by nojaf** [comment]
As it is only a warning, I can temporary live with this.
Feel free to disagree @dawedawe, @josh-degraw.

**Review by dawedawe — APPROVED** [review]
Yeah, I won't loose sleep about that temporary warning.

**Pull request merged**
