### PR TITLE
Feature BlankLinesAroundNestedMultilineExpressions

### PR DESCRIPTION
**Pull request by nojaf**
Related to #1370.
I still haven't figured out what the boundaries of this setting are.
Full transparency, this might make it into v4.5 or it might be removed altogether.
This PR is an experiment and needs further triaging.

@Smaug123 would this be something GR would enable internally?

### CODE REVIEW

**Comment by Smaug123** [comment]
We would probably enable newlines around multiline expressions (as Fantomas currently does), yes.

**Comment by snuup** [comment]
I have a question regarding BlankLinesAroundNestedMultilineExpressions:

In the web demo, I can turn this feature off, which gives the formatting result I desire.
Inside Visual Studio I cannot find this configuration (F# Formatting 0.8.4.)

Is there a possibility to configure this in Visual Studio?

**Comment by nojaf** [comment]
Hello, this is a relatively new feature that has not been released in a stable version.
I'm unaware if this already found its way in the Visual Studio extension.
@deviousasti any ideas?

**Comment by deviousasti** [comment]
I was sort of waiting for F# Lint to finish the move to FCS 39 because Fantomas requiring FCS 39 would cause it to crash.
I guess I'll deploy it now and try the [scream test](https://twitter.com/shanselman/status/1247249888066154497).

**Pull request merged**
