### PR TITLE
Format long member binding and constructors according to the F# style guide

### LINKED ISSUE #868: Possible wrong indentation for functions with parameters over multiple lines
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKAXAngB0WAaogE4DOAlrAHYCyZJAtgIbrQAWAIgK5FmUDm7RCWJlGAGzIAvZhUoBRAB7RE2dLLAAKekJKM%2BiNCXQ9%2BAGjC9KxRctWy0NlWqoBKMAF4AOkU%2BUIEXlYRdDBBYR5xKRkqRzsqLR09RHNLayUnWRdIU3AoYXQ1fhJUMABtXIhQf39IABIsXBLIXnRsipragDdxTmQ0curqgAYcwZqASUokSnQAZWxGZQA5Tno2sYgAFnaIAF12gF9R-yrBuoa%2BqBb1s66ey4GNgEZjscgABSSAdTJ4dFYbmMABxDHZgfbVI7tU7Vc44S6QABGsFgYkBHW6Yl6JUeYwATK8zrNEPQyHAxFQAILoORTADyADMADK8ZCE6oM8TCMEQ-xQ6owjoXJrI1HoiB1THY-pgiAAZnZNXmi0QACFEAzYEREJ8iIxtOhiOL-MZejzDoTBRL6vCRSi0YrJfccbKwJtFRLlcp1ZrtUzYAB3YjQRjCSadWAh5yUY0QU2Ic2Qy1guGNNBI%2B3Gp1Yh6ugCsHqgXrVGq1iAAqthcEQQ2HKBGo7JY2BOWJuWNeRB%2BScUza01BRQ7e1LcxswAA2QuQYs%2BssAYTEoZIc6oRiInGg6C1zdb7cGnbA3cqveF6cHWbuOZdY4A7FOZ6XtdQSYijYXdwmOxboSfbWfM46l7SmUrpAveCzeo%2BiArhSMbvlyn77t%2BAq-v2GZioBI7XhsACc4EqpSDKGkQK70EwzbxomfLJm8fYIuemHOjKY5PCMrrThBJa%2BogxKkuSVA7ghVFdjRtyngOAHDkxIEsS87HFoRxG8WSqICYWlFfkmP60eJ6FDrRWHMc8BLsZM0zoHSlAACpEJgPz-IJbaIdUB5HmAVpQHRdoYVJV5GWMTwKvJnGUkQsCcFMggSKSxEUeuzn%2BK5omwl56bXIxfkyc87rsdQjAKOMDJWUE8hObMrBaugPx-AChabKCmnUdpYl-lcMwXoZWUBQWuX5ZMDJkAodLVswWqKNg2okOQan5g1SFaShOmtc07UZcBuKDE8k69QoABKiBwEQ8DVQ5dVzS5yE9ktaHpb562uk8d47aFeqYHSRAskYJ21a69XCYeyVCstt0GdJG3VE8YE7UyiDoKqvDwLwfDfc2f2NSJzUpbpDF3aOzx4blnBiGoEhWKqFLQAA1qqepU7DJCWbM%2BrQaiqxwa6H7-W5HmpvRkmg5l4P%2BHibFjpASyIAGpMlugQaINZ8KCANlBkNGlJTM%2B9CvqQjl7hdC1XS1aE4wL91jnicliwA0ogKiFcV8uTEz2gslYusJXsl3HtdfM%2BabeP4iZYuzMYZLoNQCBshzQno4euS7MczQkAAYuQJScwcQA)

The parameters to the function might have invalid indentation after formatting. The problem is that the formatted result below adheres to the F#-Styleguide (see [Place parameters on a new line for long member definitions](https://docs.microsoft.com/en-us/dotnet/fsharp/style-guide/formatting#place-parameters-on-a-new-line-for-long-member-definitions)) while the compiler prints indentation warnings when compiling:
 
>warning FS0058: Possibly wrong indentation: This token is displaced compared to the context beginning at position (xx:xx). Increase the indentation for this token or use the standard formatting conventions.

_(roughly translated)_

The compiler wants the parameters to be aligned with the braces, for example:
```
type T(A: string, B: string, C: string) = ....

(* to *)

type T(A: string,
       B: string,
       C: string) =
....
```

The first parameter can either be in a new line or the same line as the opening brace. The equals sign can either be on the same line as the closing brace or on a new line. I personally see the example above as the cleanest way.

#### Code

```fsharp
type VersionMismatchDuringDeserializationException (message: string, innerException: Exception) =
    inherit DeserializationException(message, innerException)
```
            

#### Result

```fsharp
type VersionMismatchDuringDeserializationException(
    message: string,
    innerException: Exception)
    =
    inherit DeserializationException(message, innerException)

```

#### Options

Fantomas Master at 05/24/2020 18:24:52 - c23aa7434b68eb3457a0e31b2d0f7bfa94eedde4

| Name | Value |
| ---- | ----- |
| `IndentSpaceNum` | `4` |
| **`PageWidth`** | **`80`** |
| `SemicolonAtEndOfLine` | `false` |
| `SpaceBeforeParameter` | `true` |
| `SpaceBeforeLowercaseInvocation` | `true` |
| `SpaceBeforeUppercaseInvocation` | `false` |
| `SpaceBeforeClassConstructor` | `false` |
| `SpaceBeforeMember` | `false` |
| `SpaceBeforeColon` | `false` |
| `SpaceAfterComma` | `true` |
| `SpaceBeforeSemicolon` | `false` |
| `SpaceAfterSemicolon` | `true` |
| `IndentOnTryWith` | `false` |
| `SpaceAroundDelimiter` | `true` |
| `MaxIfThenElseShortWidth` | `40` |
| `MaxInfixOperatorExpression` | `50` |
| `MaxRecordWidth` | `40` |
| `MaxArrayOrListWidth` | `40` |
| `MaxLetBindingWidth` | `40` |
| `MultilineBlockBracketsOnSameColumn` | `false` |
| `NewlineBetweenTypeDefinitionAndMembers` | `false` |
| `KeepIfThenInSameLine` | `false` |
| `StrictMode` | `false` |

### PR DESCRIPTION
**Pull request by nojaf**
Fixes #868.
Notice that not everything is possible to adhere to the max page width.
For example:
```fsharp
type Foo =
    static member Deserialize(loooooooooooooooooooooooooooooooooooooooooooooooooooooonnnnnnnnnnnnnnnnnnnnngggggggggggJsonVaaaaalueeeeeeeeeeeeeeee): SomeType =
        Decode.SomeType
            loooooooooooooooooooooooooooooooooooooooooooooooooooooonnnnnnnnnnnnnnnnnnnnngggggggggggJsonVaaaaalueeeeeeeeeeeeeeee
```

I think this is an acceptable trade-off for now. I'm open to discussing this though.

### CODE REVIEW

**Comment by knocte** [comment]
> I'm open to discussing this though.

How about:

```
type Foo =
    static member Deserialize(loooooooooooooooooooooooooooooooooooooooooooooooooooooonnnnnnnnnnnnnnnnnnnnngggggggggggJsonVaaaaalueeeeeeeeeeeeeeee)
                                                    : SomeType =
        Decode.SomeType
```

**Comment by knocte** [comment]
> How about:

Please note: https://github.com/dotnet/docs/pull/18793#issuecomment-640905944

**Comment by nojaf** [comment]
Sounds reasonable, I would like it to align with the start column of the parameters.
As you can see [here](https://github.com/dotnet/docs/pull/18793/commits/bd6110607c0907148c4ef6e033d5c3e910c2eda1#diff-eed63f6624dbb527e2e9533697f1ff6bR125).
It looks slightly further in your example @knocte.
Not sure if that is just GitHub formatting.

**Comment by knocte** [comment]
> It looks slightly further in your example @knocte.

Well, in my preference I like to indent the return type 4 spaces more (if indent=4), but I can live without that.

**Pull request merged**
