### PR TITLE
Retain significant whitespace in nested, indented #if directives

### LINKED ISSUE #1866: indented #if directive inside another non-indented #if directive drops significant whitespace
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKBiAlgMzAMQHkCAdAJ2IDszKIItcAhAQQCVqryLax1EL4c7dr345IAGnBQAzogAuczBQDm01GADaUiKG4RIAEjkBPAA7I0kJXInbahgG4BDADYBXC5rvcADJL32AJL8fHIAypgAXsj%2BAWAALN5gALp2AL6xOkmGJubqVhQ2mfYGzu6eWnFgAIzF3JAAsk4AHgAySoitfMpyABa2VdUATD5JqdwZdrp6OWaekABGsLAuAzOlrh7qlXFDdfZhiAC2mHAusBRMcgCi-ATY7RQxSRDYrrJj6cXT9UZz%2BUsVmtfmUtmgdgEAMz7fRhUxOaCIBiIbCwUiIAAKTlITiO8kQpGBejkpA8nwm32yfzylkBq32jk2FReCRhUDhCKRKLRnVgAHcCdAnLJgg5YELFBcidwSWSAuNaJNuD8Srl5nTpVANuVtiyAKxsyAcxHI1HogCqpnMpCFIooYolmClbLeLg%2B8q%2BUypaoBy3pVNBzKqADZDcauWbEABhFzC6RRi7SWXQORozWvd6IcmKykBWY0qAahnasFeKoAdjD8JN3PRDWOCwJ6bArvdegVECVtBV%2Bmp6r9msZOvBLIAHFXOaaeQnzhRm62sx6KV6833fUDi4HdVUAJwTxFMbByAkJo5HJzN2WL9ue5Xe-60gebpnbuLVPwso3ViM8w4nM7OiyC7Zp2ubrD6j4bgGL4joMtSfuGh7HqQf6nCsgFVFeIFgF2WSrhBhZPtBw5lm%2BeyfsESCFAQFAACqkMYADqmB9POmbYbhYA9lqBGLERq5brBb7Qgh35MKQsBuPwAAiiAuJgJzIZepLXtwHY4WBvy8dYg4lkGb7xIaTTNIE2C0b0fDXG6iBhL0aJyMx8CsWy8SjEuOYruBD5QDpz4kRCejVAan7GcE2CYM0BDWk4qakNczSmOi0jSE6c5snqbk3sud74d5BRFMRpYBdw1ShiFLQsIgcCkPAjnOSyrkcZpqp5b5hX6QE1SVuVzSVdV8AAHJuEcjakPcgTHkcahstUTWeVpeVHG4LiKPJTx4Gi54KAStH-H5RUstU46fn1aLwA0y2rR0G2kFtSmGtAvTYgiyEAPp8pgTn9HNOVeQW%2BW6YJpGdXuPXiTixgEKQ7RJnV-QuZlam3t297-W1AkwcDegjEZLTg04kPQ5gSZDSNBLjZN02HT9KO5f9S0rZga2IDdd07Xt7WvgEQzwVUkD44TMNyBdjPM6zMX3Z%2Bj3PSmBLvZ9rE03hf3zOj6xA8VtBDORfPGQAakyDBKAIKhw82jXuaB80tWjhSA5jmsQEMIm6y0eBSSmqVG6IpsK-DDWI7Q6mcdx%2Baq3b%2B0ddjhk9dJsByAA4vI8WJYgyWpWb6WBxAwfNb2vFFpzQnc8FuuXUzHQMOc0AANYMDitfyNINFhLi0YrMNaVAexlsadb%2Bd5YXGP%2BSyQxlXzA2IHyzPInIAp8Lt5iyeFFAsalTD8PWZOkFTVTAb3Ieo-2UHDwdVRDN1fMANKIIgpimeZfDBK3eKPM8e891lHm-QttsFafUduBDGOq7ZoVkTjSF6JnAOSsuJH3XP6ABXNsagz5hEFQLhEDiWUMNUIjFEALAaAgd%2BcR95fytj-G2x9EHqwdiySEH4%2BZMHksoCg7sKCewuBEVhMU3DolorASioQYqpTYtZWBoc1yQRoSCOhVRIS8ziPzFaBIKAiIcLyFQW9RrLyUGvRMYi2xI2yrTFWCD7Yj3kTrJRItFBv1aLiBY8AnAxlgClFQk9p4dEMapIOyNla-2oRYs%2BcRIQuyUdJYmTgFiYPAcTXoYRjCFBaD4iR8DLB8HgPcN%2BYQTCYOCYA2gkIY581uFkh43iHqkBcNgSAaS6ZBMjsg7gkJS5KJvnfIRhRgj1ycBw-2H9xEHzzjxQe-FaGWNCePJRVc%2Bk1zftIcSkl%2BCTyTIgc65dmYpySilAxbIsLDP7qM-6Q8JkhKhJfGZ2IpzokidIaApAFJKBius80q8LiyWgLGHEkou6DKMX4kxASqHmKacXPQkIQFKNyY8lMRCkCpIPlIZIsQrDSDwCldQwE0hAA)

#### Code

```fsharp
#if FOO

    #if BAR

    #endif

#endif
```
            

#### Result

```fsharp
#if FOO

#ifBAR

#endif

#endif

```
            
#### Problem description

The whitespace between the inner `#if` and `BAR` is dropped, resulting in invalid code.

#### Extra information

- [X] The formatted result breaks by code.
- [ ] The formatted result gives compiler warnings.
- [X] I or my company would be willing to help fix this. A PR is incoming.

#### Options

Fantomas Master at 08/11/2021 17:06:14 - 383b729f46ebc01dde282967c68337d5ad55fa17

Default Fantomas configuration

<sub>Did you know that you can ignore files when formatting from fantomas-tool or the FAKE targets by using a [.fantomasignore file](https://github.com/fsprojects/fantomas/blob/master/docs/Documentation.md#ignore-files-fantomasignore)?</sub>

### PR DESCRIPTION
**Pull request by kentcb**
This one was tricky to debug, at least for me. The root of the problem was that `getTokenizedHashes`' inner `processLine` function was rewriting some tokens with an offset, but not adjusting others. This meant that the significant whitespace ended up _before_ the `#if` rather than after it where it belonged.

Fixes #1866

### CODE REVIEW

**Review by nojaf — APPROVED** [review]
Kent good sir this is a wonderful fix. Many thanks for this!
Apologies for the slow response as I'm currently on holiday with limited access from time to time.
Would you like to have a hotfix release for this problem?

**Comment by kentcb** [comment]
No problem at all @nojaf - I hope you're having a great break!

No need for a release for me yet. I've got a few more fixes to do before Fantomas can successfully format our (complex) code base.

**Comment by nojaf** [comment]
Hi @kentcb, how are things going for you?
I wanted to follow up on this as you made some PR's that felt specific to format a certain codebase.
Any luck? Anything I can help you out on?

**Comment by kentcb** [comment]
Hi @nojaf! Thanks for following up. Unfortunately (fortunately?), I spend a limited amount of time on open source work these days, and I've prioritized some other projects ahead of these changes. I do plan on getting back to them, but might be a little while before I do.

**Pull request merged**
