### PR TITLE
Fix documentation links

### PR DESCRIPTION
**Pull request by alanlomeli**
Was verifying all documentation links, caught these.

### CODE REVIEW

**Comment by alanlomeli** [comment]
`F# source code formatter, inspired by [scalariform](https://github.com/mdr/scalariform) for Scala, [ocp-indent](https://github.com/OCamlPro/ocp-indent) for OCaml and [PythonTidy](https://github.com/acdha/PythonTidy) for Python.` PythonTidy seems dead, should I remove that example?

**Comment by alanlomeli** [comment]
`The input source code string is converted to an [ISourceText](https://fsharp.github.io/fsharp-compiler-docs/reference/fsharp-compiler-text-isourcetext.html)) internally.`
This reference doesn't seem to be documented there anymore, any thoughts?

**Review by nojaf — APPROVED** [review]
Thanks

**Comment by nojaf** [comment]
> PythonTidy seems dead, should I remove that example?

Maybe change the link to https://pypi.org/project/PythonTidy/

> Any reference from https://fsharp.github.io/fsharp-compiler-docs/reference/ doesn't seem to exist anymore,

Yeah, this is related to https://github.com/fsharp/fsharp-compiler-docs/issues/974

We could change those links to point to the Fantomas documentation.

Example:
https://fsharp.github.io/fsharp-compiler-docs/reference/fsharp-compiler-text-isourcetext.html
would be
https://fsprojects.github.io/fantomas/reference/fsharp-compiler-text-isourcetext.html

**Comment by nojaf** [comment]
Thanks!

**Pull request merged**
