### PR TITLE
fix long tuple formatting with lambda or match

### LINKED ISSUE #1269: tuple with match formats to invalid code
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKAbRAXMBDMAvGADqQASi66spxATsQHYC2uW0AFnmAO4CWWDvSYQIAHxKQAZnzoBnLKTABaAHxgAjMMaiwE0nMRxG8JWrAAmbboA0YANoBdSDfBRDWLH0YBzOagc3CFBdCEgAEiwATwAHZDRIbywXINEIgDdcdABXeMDQ0QAGVwKwgEkTREYsAGU%2BAC9kEtKAFlSIR1SAX2bg9qhI2LzE6pSCjKzcgPt%2BiA1e0MgAWVwADwAZb0R1qp9BMdKNC0L%2Bzt0e1JDFwbiAyAAjWFh0A90JnLyZ0ssFt5rEZh8ODURgAQSwAFETAB5KSbRhNWZgKRZQynboLK5vG7DR7PV5pcKZD7TJEAZl%2BaRqMVw0EQACFEFJYHREAAFXB0XDMbCIOgE3RYOi5dHnTH9CLRW4JPEvSnvKZoL6tSlham0hlMlnbWA8PnQXCGCrpWAGrywRgC0RCkUFM6iC66LGEqW4p5yiVEyafJEAVlVUHVdMZzNZAFUYnE6AajYwTWa%2BBarRAUeg0XaMZdPa67rKrQqfd8AGwByBBzWhxAAYXQhrkVYtCmF0CwLOTyNRiFFDvF4xxufd%2Ba9JKVSIA7KXyyHtUsAfc%2Be3U%2BnQvaII7RM6wv2ZYP5cPFflSgAOSc04Na1kNkGLzvdte9645nf4vfEg-KgoATlPGtBUiwfINswrDtjaXYZmKWZ9k%2BUB5q%2B3qkt8GjFEiZZnhW2r-ICwJJgGS7gSumZOtmQwDi%2BnpvoWhzzKh5Z-gBdBYUCzy4UiYF3mA659NBpHPh6faUYhhwWKWFRINU0KMAAKnQUQAOoCBwN5pgRuirpxD7YjBDy7hRCGjkhFK0ehoJ0LA2QmAAIpQfCAgxoHCqpojqVxYCbgM2lJEOgkGYcLSlisqxlFIUkcFUEIqTUHAslgCnwPsAYtCcEE9lBj68VAXnwSOh4FBo-qoYFFQyKs0JRmwLIQqsMSsnIciJpaAa%2BslhGQcRPHSplozZe%2BSIaCWhVrAASkYLLwHFCVIklHGue5koZSMyQ9VReUToNqwjXAdDwAActkzDznQsJlABzD%2BAGGgzZpLoLcw2ToF46BbAAYiyrCeHyUmkctQl5SeqGbWNSz3Y9L1vWw9mlpwnK0gxAD6-DxUpV1pVpC1ZXpOUfqEGjfutplclE0J0JsCgTUpiUtWpREbiRnWLd5%2Bm5aExwBWsBO4ETJN8Aoe0HXyx2nedfUo%2B16X03dD18E9CKvXQ70MV9tw-b5BQWDR3yQBzXOk1gwNSzLiBywrC5QxwMMtnyCN8EjkCi7THXDBjAlM9jugWCJ60AGrevS3jwN4Pjk%2B200pfeqM3fTzvXD5zPu0ZmuBc9Fktg1fsmIHweU-b3Hi073WY713wWP562WbAWAAOLYFVNWIHVDVZ36VPOTTudo-TcGFytLMFYnIPS1s9LUNAADW9JcmP2ByJJNTctWzz7Y1SL4Tnbl0265Eu1jSIWANms7YgPCG4yWB6lUSuINZMiMAIDWgiYs78-IynLtTbUO3nZH8THru72tmsADSiBEAxGCqFKoFQ548nhIib4q8w4aQjluTyBdt5F1KBYf6ic1gRUBHIDgTdvih1aqlMWHdN4-2xLHN2ogLB401nUXwmBTI%2BH2lUWKiB7hLAQHA0oCDSHh3IZHShjMd7fDJChTWoIno%2BEYMnRgqcLR1DkWwbIrIpKwDEhwtgDVX5OQ6G3dejtv5iIwQUMkGtShawenyRguj0g6l8E-Q619vB30bPotec1tywV0ugnuugySe37lLWB6xuT3HgLgGssB6q%2BEPsfLYXjEGzQ3qYlWcdRBkgTtYyyPNcD3EwHgnmHAahRGqGsFJgikHCJQQtKo8BYSwJqNETAZjAnZNLprKETS4TJKhnQdAUg7apOuvUzu-jf7iNKGSPu1jWl0CBHrXh1T34OjcI4ZoiQ5DPXqgEVeXQgA)

#### Code

```fsharp
let a = "Hello"
match a with
    | "first" -> 1
    | "second" -> 2
    , []
```
            

#### Result

```fsharp
let a = "Hello"

match a with
| "first" -> 1
| "second" -> 2,
[]

```
            
#### Problem description

When formatting a tuple with pattern match as first element fantomas puts comma in the wrong place and generates not compilable code.

Expected formatting:

```fsharp
let a = "Hello"

match a with
| "first" -> 1
| "second" -> 2
,[]

```

#### Extra information

- [x] The formatted result breaks by code.
- [ ] The formatted result gives compiler warnings.
- [x] I or my company would be willing to help fix this.

#### Options

Fantomas 4.2.0

Default Fantomas configuration

### PR DESCRIPTION
**Pull request by ThisFunctionalTom**
This should fix #1269

### CODE REVIEW

**Comment by nojaf** [comment]
Hey @ThisFunctionalTom, apologies for my late response.
Many thanks for taking the time to submit this PR, this is much appreciated.
This looks good, and you did make a valid remark when it comes to

```fsharp
1, 
"Hello", 
match "Hello" with 
| "first" -> 1 
| "second" -> 2 
| _ -> 3
```

I'll try something out on my side, maybe we can make the check more specific to only apply if the tuple has a `match` or `lambda` followed by something else.

**Comment by nojaf** [comment]
@ThisFunctionalTom does this make sense to you?

Also added an extra pattern match so it fixes #966 as well.

**Comment by ThisFunctionalTom** [comment]
> @ThisFunctionalTom does this make sense to you?
> 
> Also added an extra pattern match so it fixes #966 as well.

Yes, this looks better now. Thanks.

**Comment by ThisFunctionalTom** [comment]
Ups. Clicked wrong button. Sorry.

**Review by nojaf — APPROVED** [review]

**Comment by nojaf** [comment]
Thanks again for this PR @ThisFunctionalTom

**Pull request merged**
