### PR TITLE
Only keep collecting line comments if they are not separate by a new line

### LINKED ISSUE #920: Newline between comments should lead to individual comments
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKBtAPAQQDa9gHcA5AV3wBkBLAF0QCcBDXAPgF0AdejgOxoE8ADojABJAKIAPQbHo0AzmAC8XXhAiMARvJpNoNMABFGNRgGVENNMdMWaZ0zSrRVPdWC069Bm4wBqVIiE1ib%2BgYQOJs6u7p66jPpgAOJMggAWAEzwaCmM6VmRTi7cbupx3mAAKlQAtoi4VDyIaNV1DU2F0SXuAPQ9Htrxia31jc1VtaMdjs6dxWplgxXEloSyANZoKzRr9Otzrq59YALCYFh4BCTkuNR0TKxsYACysHV8AMKwPF6k%2BrIARmUR367iw4hqtDAHEgABIAAwAClhAIAdOiAJQw9gDLwJAyiHgAN1g63GAH5GoI0K93jRCYJSAYAFRgckAM1kNRMNLeiD4ADEuSYzMJoFR2c4ot8wKzyV5nFYwJpYLBcGAALQsF58viHErHU4iC74IhkSi0BjMHG0-k0L4-XR-GiyDLAg2g9TgyEGGEI5FozHYp7lfFiYmkilU3l0hlM2Vszn0blK22C4X2MUSqVOGVy3CMHgAc1IjCL4wVxYT8t0irQKrVmu1aZo%2Bt4hqEIhbDt%2B-3o7vbnogAFUMphu99ey76ACADQ6uk9p19jIsSCz8BQeSWJzF%2BSoc6biCgdwQOFGg%2BQRo0ddH9RwonMUjINDoO-ueEb0-3wlIPiihJEDIGpb2-CAABZ3zANg7wAXy-dQT1Pc9O0va9QOQ2FH1wZ8DzfMCwDnKCzwABTLRAAHUqHgGg0gw78AQyeEoJg9x4LvJD3BQ4RLwbXB6PvLCnxfQ8CIyBDv0gCxITgAgeGwGhxB4eAAHl2WoJoBPcdlmG3Fi4IksBOMEi80EgPitKgIScJE-CwIAZkMriAOgRAACFECTRAyKYOp7ksiAnUQfS2MM4yz1hUyoAspyrOw3DX2IsBwNis8XPczzZEQCgiAYaBGG3QkSXy3MeACk56GfEL1HY9xwqsqLzNVfjYofYS8KSgBWVKoHSjyvOHQRhHofLCojEqqG%2BcqdNwPTv1Ymqwqg7iRKatVLLamyOoIgA2HqpMEQD%2Bqyj4C3keQl0qvtpt04L5oMjjlsi1CzJip74tspKAHZ9r6zL6EQZ5EBqTQGBu2a7tPBaIFqxCnsat7JOshLRLAgAOX7Dtc46Aa%2BOTwbmqGHrq%2BGXui5qNuRz6CIATkxwDsHZe4vhqblyqC6qYaWpGEYp1qqe2sCAU-JKDqO-7EGk5w1SmnqZsJ9xobAWHj1JnjXr5972sSgiASIgixdcxn7il2TZaSjn7tCx6ebJtaWq1radaF8TRd-O0VJ4Sp6H4KjaIJyHFeJuHbfV8n1v5j7BYYxzRfS7B6FgUhlMMUYfTBnrLaJ62SdD1b0Mj7XUYYlLReeRhJFEdlKjSflxAhsw0lkGgqJouievA5ircWm3MMagvHZRuyGO6suK8JSVJBU4aTFkKRBAB87JrKnrOq77Oe9zvu7YHpGo%2Bdhi9rHyQACVEDgeh4Fb-2O-XoOc5D7ew6vPhKf34vTwBH7j4Tph%2BBU%2Bg1AdDX3bklTunNlbcyfvnV%2BhcnYf3cACDGx8-DCTco0eAjQiwgPKuA7uXNe5cWes-XemF37D0-nTY%2BApk76GXug5SWCcG3wgSrIyatVqIzIUXCh7gmL7WeOQJw7R3IEGgOsNyegyQKE9mYRgdQ8akBqCvJK8tA7qCVmw%2BqK1eKaz3jwpKGR9ZgUgCsQgIiPI7EQPySonZU6Sh4LQZe2BlJAxBgwfcctbqsKgUQ3mEdB7UzAhkV2BsADS1jBBVxrvyQkci6gaWQF4iGPjCEmTtlwoh5DDGxwNg4egipXhIADqwzcbAEJXnkAKeQVADxqJALBIAA)

The second comment trivia should be split into multiple trivia.
Stop collecting when there is a gap in line numbers.
Related change: https://github.com/fsprojects/fantomas/commit/c854fdbbea00ad3d9d8267223cea64f660e6439c

#### Code

```fsharp
[<AllowNullLiteral>]
type IExports =
    abstract DataSet: DataSetStatic
    abstract DataView: DataViewStatic
    abstract Graph2d: Graph2dStatic
    abstract Timeline: TimelineStatic
    // abstract Timeline: TimelineStaticStatic
    abstract Network: NetworkStatic

// type [<AllowNullLiteral>] MomentConstructor1 =
//     [<Emit "$0($1...)">] abstract Invoke: ?inp: MomentInput * ?format: MomentFormatSpecification * ?strict: bool -> Moment

// type [<AllowNullLiteral>] MomentConstructor2 =
//     [<Emit "$0($1...)">] abstract Invoke: ?inp: MomentInput * ?format: MomentFormatSpecification * ?language: string * ?strict: bool -> Moment

// type MomentConstructor =
//     U2<MomentConstructor1, MomentConstructor2>
```
            

#### Result

```fsharp
[<AllowNullLiteral>]
type IExports =
    abstract DataSet: DataSetStatic
    abstract DataView: DataViewStatic
    abstract Graph2d: Graph2dStatic
    abstract Timeline: TimelineStatic
    // abstract Timeline: TimelineStaticStatic
    abstract Network: NetworkStatic

// type [<AllowNullLiteral>] MomentConstructor1 =
//     [<Emit "$0($1...)">] abstract Invoke: ?inp: MomentInput * ?format: MomentFormatSpecification * ?strict: bool -> Moment
// type [<AllowNullLiteral>] MomentConstructor2 =
//     [<Emit "$0($1...)">] abstract Invoke: ?inp: MomentInput * ?format: MomentFormatSpecification * ?language: string * ?strict: bool -> Moment
// type MomentConstructor =
//     U2<MomentConstructor1, MomentConstructor2>



```
            
#### Options

Fantomas Master at 06/13/2020 12:50:29 - f502c77f041ab51647d9f271932036d4de75de58

| Name | Value |
| ---- | ----- |
| `IndentSpaceNum` | `4` |
| `PageWidth` | `120` |
| `SemicolonAtEndOfLine` | `false` |
| `SpaceBeforeParameter` | `true` |
| `SpaceBeforeLowercaseInvocation` | `true` |
| `SpaceBeforeUppercaseInvocation` | `false` |
| `SpaceBeforeClassConstructor` | `false` |
| `SpaceBeforeMember` | `false` |
| `SpaceBeforeColon` | `false` |
| `SpaceAfterComma` | `true` |
| `SpaceBeforeSemicolon` | `false` |
| `SpaceAfterSemicolon` | `true` |
| `IndentOnTryWith` | `false` |
| `SpaceAroundDelimiter` | `true` |
| `MaxIfThenElseShortWidth` | `40` |
| `MaxInfixOperatorExpression` | `50` |
| `MaxRecordWidth` | `40` |
| `MaxArrayOrListWidth` | `40` |
| `MaxValueBindingWidth` | `40` |
| `MaxFunctionBindingWidth` | `40` |
| `MultilineBlockBracketsOnSameColumn` | `false` |
| `NewlineBetweenTypeDefinitionAndMembers` | `false` |
| `KeepIfThenInSameLine` | `false` |
| `StrictMode` | `false` |

### PR DESCRIPTION
**Pull request by nojaf**
Fixes #920

I'm open to suggestions when it comes to using that `mutable`.
Had no immediate idea of how to do it without it.

### CODE REVIEW

**Comment by knocte** [comment]
> I'm open to suggestions when it comes to using that mutable.

Use List.fold instead of List.takeWhile?

**Comment by nojaf** [comment]
@knocte 
```fsharp
rest
|> List.takeWhile
```
`rest` in this case are the remaining tokens of the entire file.
Doing a `List.fold` followed by a filter would go over way to many tokens.

**Comment by jindraivanek** [comment]
> I'm open to suggestions when it comes to using that mutable.

Something like

```
Seq.zip rest (headToken::rest |> List.map (fun x -> x.LineNumber) |> Seq.takeWhile (fun (t, currentLineNumber) -> ...)
```

**Comment by nojaf** [comment]
@jindraivanek thanks, I'll try it.

**Comment by nojaf** [comment]
@jindraivanek ready for review.

**Pull request merged**
