### PR TITLE
Put stars in long tuple in long signature at the end.

### PR DESCRIPTION
**Pull request by nojaf**
WIP, related to https://github.com/fsharp/fslang-design/issues/644.
Style guide would need an update before we can merge this.
@dsyme and I did discuss this in person though.

### CODE REVIEW

**Comment by baronfel** [comment]
Re: style guide change, would that also require FSAC changes to align with this formatting?

**Comment by nojaf** [comment]
That would be nice, but I'm really jumping the gun here by already having an implementation for this.
One benefit is that we discovered when you need the extra indent (after tuples) for example.

**Comment by dsyme** [comment]
@nojaf I guess given our conversation at NDC we can consider the stile guide change pre-approved. I'll work on a PR next week

**Comment by nojaf** [comment]
Yes, I was thinking along the same lines.

**Pull request closed without merging**
