### PR TITLE
use fallback in Expr.PrefixApp when operator starts with "%"

### LINKED ISSUE #2796: Adding space after prefix operator breaks code
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKAbRAXMBLAdugYmABQB%2BApJQJR7xgC8e%2BOu8AOgE4f7e%2BYcAMzABDMACMmYsAGpJ-Pj0LYwQ2LDJ1mI6h0gBGAOz6weyABYATPsgAacFADO2LAQDmT1GADajiKAQQVAAJFgAngAOyGiQBFj2-kGQIQBuougArjG%2BScEADA7BwZAAkvhIrADKuABeyEXFEBZ5YAC6SQC%2BjQGtKRHR3nGsiU0p6Vk5fk0QBj3FkACyogAeADLEa4j47lgAFqMzBlb5rR3B3UmBC2FROZDb8ADyQhv4iFURmIclaRnZ3mmMys8xKAFEKi83g1WhBIOghJAzl15tdfgN7hINOgfsk-pNAbCwABmUHJcouLhYABiBAyADlEAB3IjvXHBLBcbLIi6ovq3QaxLGwHFk8b-KZEixkuFVSKiaCIABCiHUXEQAAVRFxRABbbCILjsoKc7lNc5BS7BNF4jFDYWi-kTAFoIFNACsMqgcoVytVsHVa1gTMN0FELnKqVgYbcsHwxogpsQPMtfLGAsx2ON4oJrqJADYvZAfYqVWrEABVSLRLhhiP4KMx3BxhNqDIuFMQK1BG1wjP2rNi-Eu3IzMBGIslv3lgDC6HDThncacpugWADraE7eT5pRV35dqFg6dEsJY4AHJP5aX-erFohdRJDZvt52wN3eunD1AHdnh5KxwATivX0ywDRAl3QFsvS3dAO13Xl9y-O4BxFP9nQAo5CiJYtr0QABBIQsENJddV1URWyTN8PzAXtQm-SBfyHDCzyOOYcKnMD1SqB9cDgKD4xg18ENTJCbgYpiT1zUcjhBDi8MI4iuB43U%2BJFaCiSokSuzTcSUKPNDmNPPMxwMUl5N9fCuFgTIKgAEUQIhVKUyiuR3YoLR0sT0X0qB4nQ4yZKaAxpRw5YVlKIQABU9m2Ko9gDLAAHV2H2VtTm099dJ8wU-JGIzpLdYoDE9MLVkimLtjBOCPgSqkUvgNKvXzDKPL3a0D184YEgKkciuCAxCzKiL8CEXAVieGtRHXLgwRWSJ1ScJxm0Eolz1a4JPKy7zbS6-zesw4KJ2GgAlRA4C4eAGqaqUNqCLaaLo-o9vyqS%2BqJAxL1O86A3gelMkfQ0XlKYjdS8L0DGo7LdtyyBdUydA3FZRBqQDcisCUqKUIO1jguAnCzou%2BBFgRpHiFRrh0ZcotoD2bUFSUgB9JlUoOKGdr7Bj9rew7ihOItwqsnVwieLgNhXa6Di9db2Y65DYe59MWJM4F2LHJZViF0QRbF3AV3%2BwGuGB0HwY%2B2We062H4cR3BkYpqnDSxwYcZVporDk9WtZ18WsBJm27bR6bqZw2n6bXQ1mdZpFMsey37kVm5laCvnzPV8KADUJSVAh4A8SXWxlmPoc5l6ep53G%2BdCtPVmpWy1xW7OKjzqOvQsO6IAe4v6NLgLCqJKxSurlY7NgLAAHFsDmhbECWlb8%2Bl9v2nai35czQzy9dvmhvVxkWWIFUsBDbYncQByxvwXBY3wfCKnvQ3TbHLS2sQuW9NhySlcC-qgisY7PaIdw%2BBa74HrnGGogDpqZHVFFWA5RKhYGmitF8NVzafjfmvR0n8%2B5jisF9f%2BSl8CINSIgIMOw75Pi4GfAgl8VoPxmLBeCz9RKvxyhg3u70cH4zTqTXA0I1h6gkPAUQc5YDLR2LvZGyDGGbWXmg1hqFMGJy-kSYk2F1ZT0NLgfUrAMgAGlECIEiHA7YWByhKh1CAqWRIGHuRkS-Fe6CFHsN5sEYkasZiQCVPOfAABraETgrI2QqIyFciBiY8ORlPRay1lyuTNEwryLCYZsJdsnVxHsPFKm1FxU%2BetoBcC0XSYi8AKwXzjA5aA84dRXykbY%2B6sjaJxyGNbMm7xzEKh8dgT44RvipO-hAYkqcPF%2B1acqHU0BOlYG6b0kOOpdTRHgNHBJ20kklwVq9LBHCZjEirh4-RhjwoGwoS8LxohfH%2BNbAYfIi9O4c27u-Y8myXFBGJIPDxEj963kQCM22xBSKREyAgq%2BUSZ4xNWo-NyqDGmrycX0lR28PGfGspkFcXJIi0kIegH2Vl3AAxMXQpoNioVPX7AZRRvwk79JJH-RFnI%2BK%2BwQDCMcRKY6ODaI0OIThqTLW8ESzoQA)

#### Code

```fsharp
let inline (~%%) id = int id

let f a b = a + b

let foo () = f %%"17" %%"42"
```
            

#### Result

```fsharp
let inline (~%%) id = int id

let f a b = a + b

let foo () = f %% "17" %% "42"

```
            
#### Problem description

Fantomas adds a space between the prefix operator and the string. Note that this only happens when the string is specified after the operator. If a value is used, then formatting does not add a space.

This works correctly:
```fsharp
    let inline (~%%) id = int id
     
    let f a b = a + b

    let v = 17
    let w = 42
    let foo () = f %%v %%w
```

The current workaround is to add ( ) around the operator and value.
We use this in our tests to setup data; that's why we use strings there, not values containing strings.
It would also be more consistent never to add a space (as far as I understand it, a space is only added when the prefix operator is followed by a string definition)

#### Extra information

- [X] The formatted result breaks my code.
- [ ] The formatted result gives compiler warnings.
- [ ] I or my company would be willing to help fix this.

#### Options

Fantomas v5.2 branch at 1/1/1990

Default Fantomas configuration

<sub>Did you know that you can ignore files when formatting from fantomas-tool or the FAKE targets by using a [.fantomasignore file](https://fsprojects.github.io/fantomas/docs/end-users/IgnoreFiles.html)?</sub>

### PR DESCRIPTION
**Pull request by dawedawe**
fixes #2796 

As was discussed in the issue, we need to extend the guidance in the style guide for a real sulution (this change here is just a quick fix for Urs)
We'll tackle that whole topic for 6.1

### CODE REVIEW

**Review by nojaf — APPROVED** [review]

**Comment by ursenzler** [comment]
oh wow, thanks! Was planning to take a look next week :-)

**Comment by dawedawe** [comment]
If you want to give it a spin, it's in the latest [alpha](https://www.nuget.org/packages/fantomas/6.0.0-alpha-009)

**Comment by ursenzler** [comment]
I did. It works great from the command line and in the current EAP of Rider, but crashes when run from inside Rider 2022.3.3.

**Comment by nojaf** [comment]
That is to be expected. The API changed in `v6`, and the JB team updated their integration in the `2023.3.1 EAP`. It should work there.

**Comment by ursenzler** [comment]
@nojaf, thanks for the information. Many thanks again.

**Pull request merged**
