### PR TITLE
Go format yourself!

### LINKED ISSUE #666: Lead by example
### Description

Fantomas should format itself.
@jindraivanek what configuration options would you prefer if we pull this off?
I like to put `KeepNewlineAfter` on true.

I'm a bit worried that we will face the performance issue when formatting `CodePrinter.fs`.

### PR DESCRIPTION
**Pull request by nojaf**
Fixes #666

### CODE REVIEW

**Comment by knocte** [comment]
@nojaf good work! but quick question. Why does this get joined:

```
-    let normalizeThenSplitNewLine (str : string) =
-        (normalizeNewLine str).Split('\n')
+    let normalizeThenSplitNewLine (str: string) = (normalizeNewLine str).Split('\n')
```

while this gets separated?:

```
-        (let assembly = typeof<SourceOrigin.SourceOrigin>.Assembly
+        (let assembly =
+            typeof<SourceOrigin.SourceOrigin>.Assembly
```

It doesn't look very consistent to me. (And personally speaking, I would have preferred myself to separate the first and not the second, given that it's a func.)

**Comment by knocte** [comment]
> It doesn't look very consistent to me.

Especially because the case where fantomas decided to split lines is actually the case where the line is shorter.

**Comment by nojaf** [comment]
This actually works as intended.
The settings `fsharp_max_function_binding_width` and `fsharp_max_value_binding_width` (default = 40) control this.
It counts the characters after the `=` of the let binding and makes a decision if it should be on the next line or not.

image

Increasing the [setting slightly](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKAbRAXMA7WATgLYCG6AlgF6IAqAForgMoAOFWAcogO4Ay5uRGAAUAZywEwacQQEBzAJRgAvCPzEyVRFz4ChMhQDpW7YQHIAOhdxmFFgtcw4So0YiIAjdAE8VYLN4siLAAZgA8TLAArgTQiADysnICxtGxCUkCAHyGAIKu7l7ekAA04FBuWFjyoqhgANrlEKAQrVAAJAFBdZACWKVNrZDtAG5kUchojW1tAAxlM0MAkrhIuFhMWgOLEAAsgxAAuoMAvgutLTPDXZNQfdtXo%2BO30zsAjOeLkACyJAAe-EEvEYciwdAeizeACZZgcwMc2mdBpc2tdArdIB5YLB0BChk90BM6q9FlDPlcmO5yHB0LBcLksABRVbxEKA5DktohMhuOEI1pItoo-E3HpYnF4iDDMaEl5wiAAZk5Q1YJDiACFECFCIgAAokAgkIjYRAESWtCQTPmncnCqWddFi7G45XS57E%2BVgXbKqWqjVanW8WDcU3QFyIFYjWBh6p080QS2Ia2I21wtHdNCY53mt2yj07MAAVh9UD9iE12oIiAAqiwgrFw5HoyRY7h42BueheYt%2BRBBRc0w6M1BxS7BzKiVNPQA2EuQMsVnUAYXQLlES7pMii0CwhHbne7M17YH7zUHoszo5zBMnDU9AHY5wuA1XvoVTfueUmezbkefHZe2aujecoFgAHE%2BLBquWL6IButJtiWB7fkev5Cv%2Bw5ZhKwETqBOwAJyQdBuQhFgpobkQpDtomyYCqmXxDhiV44e6U4Fm88yevOUH%2BpWiCUkQ1I4nGSFfrRfb0Y8F4jkB46sXe7EfFxZYkWRBACUJCHUQQVo-imf4MdJWFjgxuH5u8ZJcSsaxYPEuA0AQ3gAOrkGCn5dihbTHqeYB2h0RnMXJeZse8SrKTxiC5AQ0SrAAIogFCCWp2m6ah%2BnoYZAF3Os15mSFkLelxvx-EsIT0IwjIeUwdCEFgLnwG5Ja7LCel0QZUlZb0OUscFCnvMWRX-CsITkH88T1i2hCMn8LBVq45AiZ6hYtWlbUZR1mH3D1t4kjMbyzoNfwAEqIHABDwPVjWes14knpJqKMT0W1BTtnpvI%2Bh1RYa3iJPw4iXeCTUrV5aEDplm3dS9eGQhBh0AGrPOqAjwPIAPtrsUK3T5fnphiz2mfJu1tG8hGHQAYlEuA7gtuBI6sqPkA1gPXZjrUSe1D0BbJBO9UTrQwnO3xROg1QUII6q0tAADW6qGtL2CiHZTBGnBOJREQiGeshWP3SKnWBTzr0FlCSkFpAOhizBWAhowNDovFI24K5NO5Ksb6eKatSiR5Osc3rmEG48eV9aSllmwA0ogiAsKV5W4CsyvGuy7mHiD6VgxteOQ4b0MzFCYVm8VlWCaIdBo0DvvrZz%2Bvc0HhOelChVm5suByJgUVyOrjB1YgHjfAgHJa2JbN3X79pc9hUPmaSA1m7kFByLgFNU62myLy2MS0LA1ndy2NMp55rTebr4815POfT3nB1zyLpq4HvIyIEGrfux4poOwIzubgflcZ9XAe1wesHPmEAoQfWbhIakWB%2B5IB-iPE45RDjnF6KIMmohyB1G1icIAA) (to 42) makes both cases on one line.

**Comment by knocte** [comment]
Oh wow are you saying that the left part of the binding doesn't count when accounting for the number of characters? I would never expect that. I myself only use these settings as `fsharp_max_function_binding_width=0` and `fsharp_max_value_binding_width=$max_line_length` so it doesn't affect me, but thought I would give an outsider perspective on soething that doesn't comply with the [principle of least astonishment](https://en.wikipedia.org/wiki/Principle_of_least_astonishment).

**Comment by fc1943s** [comment]
I went through a similar feeling, then changed both parameters to max_line_height to see how it went. Interesting read!

Nothing against the parameter though. It's pretty flexible. Or maybe the default could be 0 or $max_line_length instead of 40.

**Pull request merged**
