### PR TITLE
Feature/config file

### LINKED ISSUE #354: Allow for saving arguments in a config file
Fantomas should allow for inputting formatting arguments via a config file, like `.fantomas-config`. This config file could be located by convention or by an explicit CLI flag.  Having such a file would allow for settings to be tracked in source control, applied without the user having to remember many cli flags, and make it easier to run formatting via shell utilities, FAKE, various editor toolings, etc.

### PR DESCRIPTION
**Pull request by nojaf**
Initial attempt to resolve #354.
The configuration file is a JSON file according to the schema.
I've extended the public API with
- `GetVersion()`
- `ReadConfiguration()`
so tooling could benefit from this as well.

Any feedback on the public API is welcome. @Krzysztof-Cieslak I think this is sufficient for FSAutocomplete, let me know what you think.

TODO:
- [x] Update documentation
- [x] Bump version to minor

Once merged:
- Release a beta to gather feedback
- Integrate beta in FsAutocomplete.

### CODE REVIEW

**Comment by Krzysztof-Cieslak** [comment]
Yeah, I think single function for reading config is all we need in FSAC

**Comment by jindraivanek** [comment]
Great work!

**Comment by stken2050** [comment]
Please update documentation for this configuration, so probably Ionide, etc can implement their IDE settings. thanks.

**Comment by nojaf** [comment]
This configuration was deprecated in v4 in favour of `.editorconfig`.
You can use the online tool to easily grab the syntax for any setting:
https://fsprojects.github.io/fantomas/docs/end-users/Configuration.html#Trying-your-settings-via-the-online-tool

**Comment by stken2050** [comment]
@nojaf Thanks for your response. Wow, this is really great.

**Pull request merged**
