### PR TITLE
Report analyzer problem in GitHub

### PR DESCRIPTION
**Pull request by nojaf**
Experiment on https://github.com/ionide/FSharp.Analyzers.SDK/pull/119

### CODE REVIEW

**Comment by nojaf** [comment]
This is pretty cool I think:
image

**Comment by dawedawe** [comment]
Awesome!

**Comment by nojaf** [comment]
Code scanning seems to work a little differently:

https://github.com/fsprojects/fantomas/security/code-scanning?query=pr%3A2962+tool%3AIonide.Analyzers.Cli+is%3Aopen

image

But I think the sarif will work out as expected.

**Review by dawedawe — APPROVED** [review]
Great integration. The sarif support is really a big step towards a professional product.

**Pull request merged**
