### PR TITLE
More CI

### PR DESCRIPTION
**Pull request by pbiggar**
This adds .NET6 to CI, and updates the .NET5 version to the latest available.

### CODE REVIEW

**Comment by nojaf** [comment]
Hey, thanks for the update of .NET 5. As for the 6, I don't really see much value in adding this at this stage.
Is there any particular reason you want to add this?

**Comment by pbiggar** [comment]
> Hey, thanks for the update of .NET 5. As for the 6, I don't really see much value in adding this at this stage.
> Is there any particular reason you want to add this?

No worries, I'll remove it.

**Review by nojaf — APPROVED** [review]

**Comment by pbiggar** [comment]
I think there's some issue with github actions being stuck, but AFAICT this has passed all the builds tests needed to be merged.

**Comment by nojaf** [comment]
Yeah GitHub Actions appeared a bit confused. All good.
Thanks for this PR!

**Pull request merged**
