### PR TITLE
Documentation.md: add pre-commit hook sample

### PR DESCRIPTION
**Pull request by knocte**
Following https://stackoverflow.com/a/42345379/1623521

Fixes https://github.com/fsprojects/fantomas/issues/1207

### CODE REVIEW

**Comment by knocte** [comment]
@nojaf FYI I tested this on macOS (which should mean it also works on Linux) and Afshin tested on Windows.

**Comment by nojaf** [comment]
Hello Andres, thanks for writing this down.
I've added a few extra lines to manages people's expectations.
This can work wonderfully or horribly depending on what you do in your code.
Was I right to assume that you've installed the tool globally?

**Comment by knocte** [comment]
> This can work wonderfully or horribly depending on what you do in your code.

What do you mean?

> Was I right to assume that you've installed the tool globally?

Yes indeed, but somehow I had to add the absolute path to fantomas, otherwise the hook would fail :(

**Comment by nojaf** [comment]
> What do you mean?

Formatting before committing. Fantomas could mess up your code right before you commit.
So using this hook could be wonderful or horrible.
We are all working hard to improve this but I feel like we should still add a fair warning.

**Comment by knocte** [comment]
> but I feel like we should still add a fair warning.

Ah yes sure. Anyway if fantomas fails to format, thanks to #1376 it would abort the hook AFAIU.

**Comment by nojaf** [comment]
Well, that is the tricky part. Fantomas does not know what your code is doing. So formatting may have worked but it could change the semantics of the code. In any case, I think we can always add more warnings later if necessary.

**Review by nojaf — APPROVED** [review]

**Pull request merged**
